Repository LilianBittar/dotnet-blazor-ecommerce, pull requests merged in 2023-02, with the labels that each got.

#32 Search url
  src/Client/Pages/Index.razor
  src/Client/Shared/MainLayout.razor
  src/Client/Shared/Search.razor
Labels: enhancement

#33 Custom layout
  src/Client/App.razor
  src/Client/Shared/HomeButton.razor
  src/Client/Shared/HomeButton.razor.css
  src/Client/Shared/ShopLayout.razor
  src/Client/Shared/ShopLayout.razor.css
  src/Client/Shared/ShopNavMenu.razor
  src/Client/Shared/ShopNavMenu.razor.css
Labels: enhancement

#36 Cart
  src/BlazorEcommerce.Shared/CartItem.cs
  src/Client/Client.csproj
  src/Client/Program.cs
  src/Client/Services/CartService/CartService.cs
  src/Client/Services/CartService/ICartService.cs
  src/Client/Shared/CartCounter.razor
  src/Client/Shared/ShopLayout.razor
  src/Client/_Imports.razor
Labels: documentation

#37 Implemented add to cart.
  src/Client/Pages/ProductDetails.razor
Labels: enhancement

#38 Show the number of items in the cart counter.
  src/Client/Services/CartService/CartService.cs
  src/Client/Shared/CartCounter.razor
Labels: documentation

#39 Turn item into products
  src/BlazorEcommerce.Shared/CartProductResponse.cs
  src/Server/Controllers/CartController.cs
  src/Server/Program.cs
  src/Server/Services/CartService/CartService.cs
  src/Server/Services/CartService/ICartService.cs
Labels: enhancement

#40 Implemented get cart products.
  src/Client/Services/CartService/CartService.cs
  src/Client/Services/CartService/ICartService.cs
Labels: documentation

#46 Implemented User register class.
  src/BlazorEcommerce.Shared/UserRegister.cs
Labels: enhancement

#48 Implemented register page.
  src/Client/Pages/Register.razor
Labels: enhancement

#50 Added validation message.
  src/Client/Pages/Register.razor
Labels: documentation, enhancement

#51 Add user model for db
  src/BlazorEcommerce.Shared/User.cs
  src/Server/Data/DataContext.cs
Labels: enhancement

#52 Implemented auth service on server
  src/Server/Services/AuthService/AuthService.cs
  src/Server/Services/AuthService/IAuthService.cs
Labels: enhancement

#53 Auth controller
  src/Client/Program.cs
  src/Client/Services/AuthService/AuthService.cs
  src/Client/Services/AuthService/IAuthService.cs
  src/Client/_Imports.razor
  src/Server/Controllers/AuthController.cs
Labels: enhancement

#54 hoooray
  src/BlazorEcommerce.Shared/UserLogin.cs
  src/Client/Pages/Login.razor
  src/Client/Pages/Register.razor
  src/Server/Controllers/AuthController.cs
  src/Server/Services/AuthService/AuthService.cs
  src/Server/Services/AuthService/IAuthService.cs
  src/Server/appsettings.json
Labels: documentation

#55 Verify the user's password.
  src/Server/Services/AuthService/AuthService.cs
Labels: enhancement

#56 Created json token web.
  src/Server/Server.csproj
  src/Server/Services/AuthService/AuthService.cs
Labels: enhancement

#57 Clippity Cloppity Bippity Boop
  src/Client/Pages/Login.razor
  src/Client/Services/AuthService/AuthService.cs
  src/Client/Services/AuthService/IAuthService.cs
  src/Client/Shared/UserButton.razor
Labels: documentation

#58 Implemented a custom Authentication state provider.
  src/Client/Client.csproj
  src/Client/CustomAuthStateProvider.cs
  src/Client/_Imports.razor
Labels: enhancement

#59 Expose the authentication state.
  src/Client/App.razor
  src/Client/Program.cs
Labels: documentation

#61 Added a return url to the login
  src/Client/Client.csproj
  src/Client/Pages/Login.razor
  src/Client/Shared/UserButton.razor
Labels: documentation, enhancement

#62 Created user profile page.
  src/Client/Pages/Profile.razor
  src/Client/Shared/UserButton.razor
Labels: enhancement

#65 Implemented change password.
  src/BlazorEcommerce.Shared/UserChangePassword.cs
Labels: enhancement

#72 Store cart item
  src/Client/Pages/Login.razor
  src/Client/Services/CartService/CartService.cs
  src/Client/Services/CartService/ICartService.cs
  src/Server/Controllers/CartController.cs
  src/Server/Services/CartService/CartService.cs
  src/Server/Services/CartService/ICartService.cs
Labels: enhancement

#73 implemented the httpContextAccessor to access the user in the service.
  src/Server/Controllers/CartController.cs
  src/Server/Program.cs
  src/Server/Services/CartService/CartService.cs
  src/Server/Services/CartService/ICartService.cs
Labels: documentation, enhancement

#79 addCartItem
  src/Client/Services/CartService/CartService.cs
  src/Server/Controllers/CartController.cs
  src/Server/Services/CartService/CartService.cs
  src/Server/Services/CartService/ICartService.cs
Labels: enhancement

#81 Added removal of cart
  src/Client/Services/CartService/CartService.cs
  src/Server/Controllers/CartController.cs
  src/Server/Services/CartService/CartService.cs
  src/Server/Services/CartService/ICartService.cs
Labels: documentation

#83 Placing order
  src/Client/Program.cs
  src/Server/Controllers/OrderController.cs
  src/Server/Controllers/ProductController.cs
  src/Server/Program.cs
  src/Server/Services/OrderService/IOrderService.cs
  src/Server/Services/OrderService/OrderService.cs
Labels: enhancement
